language: java

jdk:
  - openjdk8

jobs:
  include:
    - stage: "Build Parent"
      script:
        - mvn -pl . clean install
    - stage: "Build Core"
      script:
        - cd core
        - mvn clean install
    - stage: "Build Bukkit"
      script:
        - cd bukkit
        - mvn clean install
    - stage: "Build Bungee"
      script:
        - cd bungee
        - mvn clean install
    - stage: "Build Brigadier"
      script:
        - cd brigadier
        - mvn clean install
    - stage: "Build JDA"
      script:
        - cd jda
        - mvn clean install
    - stage: "Build Paper"
      script:
        - cd paper
        - mvn clean install
    - stage: "Build Sponge"
      script:
        - cd sponge
        - mvn clean install
    - stage: "Build Velocity"
      script:
        - cd velocity
        - mvn clean install

cache:
  directories:
    - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)